### ISSUE TITLE
Fix building with clang++ 

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha-ametsuchi#16]
clang: v.3.9.1
Tried to build with `cmake .. -DCMAKE_CXX_COMPILER=clang++ && make`
and got:
```
[  5%] Building CXX object ../external/build/flatbuffers/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
.../iroha-ametsuchi/external/src/flatbuffers/src/idl_parser.cpp:17:10: fatal error: 'algorithm'
      file not found
#include <algorithm>
```

After manual adding include path via `-DCMAKE_CXX_FLAGS='-I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu'` it works. Anyway that should work by itself or at least some other way for providing the compiler

**Comment by lebdron** [comment]
https://github.com/google/flatbuffers/issues/4188
