### ISSUE TITLE
Extracting PageManager logic

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha-ametsuchi#21]
Current VFS implementation is pretty dumb and has logic for managing pages.

- [ ] PageManager class
- [ ] VFS doesn't need to think about flushing/caching
- [ ] FileVFS' tests probably shouldn't be fixed
- [ ] PageManager tests
- [ ] Replace f-open/write/read to non-caching syscalls open/write/read
- [ ] Interface for page strategies

**Comment by Warchant** [comment]
>LRU page strategy implementation
`ametsuchi/cache.h` implements LRU

**Comment by l4l** [comment]
fxd

**Comment by l4l** [comment]
any updates?
