### ISSUE TITLE
Inconvenient interface of serialize::* fns

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha-ametsuchi#33]
Current implementation of `put`/`get` functions has terrible iface so we should discuss how we can change it. Here's the list of use-cases and regarding proposal to fix.
Macros analogues are pretty same so I won't discuss them. Template parameters are assumed to be either a primitive type or `ByteArray`

# get

#### Signature:
```
template <typename T>
inline void get(T *value, const ametsuchi::byte_t *&src);
```

#### Issues:
1. can't deserialize array of values
2. get value by pointer (quite slower as it can be)
3. can't deserialize from `ByteArray`

#### Possible resolution
That can be done via doubling the signature:
```
// RVO is faster rather than write-by-ref

template <typename T>
inline T get(const ametsuchi::byte_t *&src);

template <typename T>
inline ByteArray<T> get(const ametsuchi::byte_t *&src, size_t size);

template <typename T>
inline T get(const ByteArray &src);

template <typename T>
inline ByteArray<T> get(const ByteArray &src, size_t size);
```
 

# put

#### Signature:
```
template <typename T>
inline void put(ametsuchi::byte_t *&dst, const T &value);
```

#### Issues:
1. can't deserialize array of values
2. can't serialize to `ByteArray` (common use-case accord)

#### Possible resolution
```
// size = 1 is redundant because it don't overhead
// so no need base signature

template <typename T>
inline void put(ametsuchi::byte_t *&dst, const T &value, size_t size);

template <typename T>
inline void put(ByteArray &dst, const T &value, size_t size);
```

**Comment by Warchant** [comment]
>can't serialize to ByteArray (common use-case accord)
It can.

https://github.com/hyperledger/iroha-ametsuchi/blob/master/test/ametsuchi/serialize_test.cc#L58

**Comment by Warchant** [comment]
wontfix
