### ISSUE TITLE
Wanted Function `getTransactions`

### ISSUE THREAD

**Issue by satellitex** [hyperledger/iroha-ametsuchi#62]
# Wanted function.
- std::vector<AM_val> getTransactions(const size_t& index, bool uncommitted = false);

It provide that getting all transactions after `index` -th in ametsuchi db. 
( But its size is very large. Actually, we should get alike `streaming` )

It will be used by new peer when that wants to synchronize transaction.

**Comment by Warchant** [comment]
I think we can give you some sort of iterator.

```
auto it = ametsuchi.iterator(N);
++it;
--it;
```
